addons:
  apt:
    packages:
    - libcurl4-openssl-dev

language: php
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phing test -Donly.units=true
